"""Pokemon Tables with foreign keys

Revision ID: 1f98860cad25
Revises: bb9b977774bf
Create Date: 2025-03-02 09:55:10.503518

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f98860cad25'
down_revision: Union[str, None] = 'bb9b977774bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movelearnmethod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('versiongroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('base_experience', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('location_area_encounters', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pokemon_move',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['move_id'], ['move.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'move_id')
    )
    op.create_table('pokemonability',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('ability_id', sa.Integer(), nullable=False),
    sa.Column('is_hidden', sa.Boolean(), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ability_id'], ['ability.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'ability_id')
    )
    op.create_table('pokemonstat',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('base_stat', sa.Integer(), nullable=True),
    sa.Column('effort', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['stat_id'], ['stat.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'stat_id')
    )
    op.create_table('pokemontype',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['type.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'type_id')
    )
    op.create_table('sprite',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('front_default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('back_default', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('front_shiny', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('back_shiny', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id')
    )
    op.create_table('pokemonmovedetail',
    sa.Column('pokemon_id', sa.Integer(), nullable=False),
    sa.Column('move_id', sa.Integer(), nullable=False),
    sa.Column('move_learn_method_id', sa.Integer(), nullable=False),
    sa.Column('version_group_id', sa.Integer(), nullable=False),
    sa.Column('level_learned_at', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['pokemon_move.move_id'], ),
    sa.ForeignKeyConstraint(['move_learn_method_id'], ['movelearnmethod.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon_move.pokemon_id'], ),
    sa.ForeignKeyConstraint(['version_group_id'], ['versiongroup.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'move_id', 'move_learn_method_id', 'version_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemonmovedetail')
    op.drop_table('sprite')
    op.drop_table('pokemontype')
    op.drop_table('pokemonstat')
    op.drop_table('pokemonability')
    op.drop_table('pokemon_move')
    op.drop_table('pokemon')
    op.drop_table('versiongroup')
    op.drop_table('type')
    op.drop_table('stat')
    op.drop_table('species')
    op.drop_table('movelearnmethod')
    op.drop_table('move')
    op.drop_table('ability')
    # ### end Alembic commands ###
