"""Removing unused tables

Revision ID: 60049a23bb18
Revises: b2f017249c2d
Create Date: 2025-03-02 16:38:20.480463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60049a23bb18'
down_revision: Union[str, None] = 'b2f017249c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sprite')
    op.drop_table('movelearnmethod')
    op.drop_table('versiongroup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versiongroup',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movelearnmethod',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sprite',
    sa.Column('pokemon_id', sa.INTEGER(), nullable=False),
    sa.Column('front_default', sa.VARCHAR(), nullable=True),
    sa.Column('back_default', sa.VARCHAR(), nullable=True),
    sa.Column('front_shiny', sa.VARCHAR(), nullable=True),
    sa.Column('back_shiny', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id')
    )
    # ### end Alembic commands ###
