"""Removing move detais from move learn method

Revision ID: 8740d5781e93
Revises: e7ba724e9f13
Create Date: 2025-03-02 10:01:41.413735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8740d5781e93'
down_revision: Union[str, None] = 'e7ba724e9f13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
