"""Removing Pokemon Move Details tbl

Revision ID: e7ba724e9f13
Revises: 1f98860cad25
Create Date: 2025-03-02 10:00:36.034717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7ba724e9f13'
down_revision: Union[str, None] = '1f98860cad25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pokemonmovedetail')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pokemonmovedetail',
    sa.Column('pokemon_id', sa.INTEGER(), nullable=False),
    sa.Column('move_id', sa.INTEGER(), nullable=False),
    sa.Column('move_learn_method_id', sa.INTEGER(), nullable=False),
    sa.Column('version_group_id', sa.INTEGER(), nullable=False),
    sa.Column('level_learned_at', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['move_id'], ['pokemon_move.move_id'], ),
    sa.ForeignKeyConstraint(['move_learn_method_id'], ['movelearnmethod.id'], ),
    sa.ForeignKeyConstraint(['pokemon_id'], ['pokemon_move.pokemon_id'], ),
    sa.ForeignKeyConstraint(['version_group_id'], ['versiongroup.id'], ),
    sa.PrimaryKeyConstraint('pokemon_id', 'move_id', 'move_learn_method_id', 'version_group_id')
    )
    # ### end Alembic commands ###
